baseURL: "https://stosa-org.netlify.app/"
languageCode: "en-us"
title: "STOSA"
# Theme: https://github.com/victoriadrake/hugo-theme-introduction
theme: "introduction"

markup:
  goldmark:
    renderer:
      unsafe: true

# Disable Taxonomies
disableKinds:
  - taxonomy
  - term

taxonomies:
  tag: tags

params:
  description: "Single Team Oriented Service Architecture"
  footerText: "© 2019-2020 Lee Atchison"
  themeStyle: "light"
  favicon: "/afs2e40x40.gif"
  showRSSButton: false
  fadeIn: true
  fadeInIndex: false
  dateFormat: "Jan 2, 2006"
  email: "unk@unk.com"
  home:
    introHeight: "fullheight"
    localTime: true
    timeZone : "America/Los_Angeles"
    timeFormat: "h:mm A"
  share:
    twitter: true
    facebook: true
  social:
    - url: "https://twitter.com/leeatchison"
      icon: "twitter"
      icon_pack: "fab"
    - url: "https://www.facebook.com/mdascale/"
      icon: "facebook-f"
      icon_pack: "fab"
    - url: "https://www.linkedin.com/in/leeatchison/"
      icon: "linkedin-in"
      icon_pack: "fab"

menu:
  main:
    - name: "Home"
      url: "/"
      weight: 1
    - name: "STOSA"
      url: "#intro"
      weight: 2
    - name: "Advantages"
      url: "#advantages"
      weight: 3
    - name: "What does it mean?"
      url: "#whatmean"
      weight: 4
    - name: "Organization"
      url: "#stosaorg"
      weight: 5
    - name: "Core Teams"
      url: "#coreteams"
      weight: 6
    - name: "More Info"
      url: "#moreinfo"
      weight: 7
